### PR TITLE
Jafix octavian mar2022 p5

### PR DESCRIPTION
**Pull request by octavianx**
fix fuzzy to line 3300.  
merge some duplicated lines to share translation.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-translations/143)

### CODE REVIEW

**Comment by Frenzie** [comment]
> merge some duplicated lines to share translation.

I'm not completely sure which lines you mean? That sounds like something that would normally all be taken care of automatically.

**Comment by octavianx** [comment]
```
Group1: 
#: frontend/apps/reader/modules/readerfooter.lua:1826
#: frontend/apps/reader/modules/readerfooter.lua:1852

Group 2:
#: frontend/apps/reader/modules/readerfooter.lua:1823
#: frontend/apps/reader/modules/readerfooter.lua:1869
```

inside the group, they were using the same texts but separated as different items.

**Comment by Frenzie** [comment]
Hm, I suspect if so you may have accidentally caused that yourself. :-)

**Comment by Frenzie** [comment]
Provided it's not about contexts they'll be merged automatically.

**Comment by octavianx** [comment]
> Provided it's not about contexts they'll be merged automatically.

I found a slight difference :   Uppercase/lowercase in the initial letter of the original english text.
'static margins'  -  'Static margins' 

Assuming it is the reason why system took them as different items.

**Comment by octavianx** [comment]
Should I roll back? I thought it maybe a mistake for I merged them.

**Comment by Frenzie** [comment]
That means they'll show up again as untranslated in the future (and almost certainly fuzzy automatched). No real need to do anything right now.

Btw, Weblate also implements a lot of sanity checks about the translated strings, see https://hosted.weblate.org/projects/koreader/koreader/ja/

**Comment by octavianx** [comment]
Sorry to this mistake. I  will fix this in the next commit. 

 I tried weblate today,  started to learn how to utilize it.
Thanks for your advice~

**Pull request merged**
