### PR TITLE
Remove transifex leftovers + add template for mac menu

### PR DESCRIPTION
**Pull request by pazos**
I'm not familiar with Weblate. Can the new resource be added to Weblate and the translated strings be magically pulled to their respective language directory as it happens with .po translations?.

Pinging @Frenzie.

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-translations/135)

### CODE REVIEW

**Review by Frenzie — COMMENTED** [review]
Assuming the format is supported, I think it'd need to be a different component. Which we probably can get but it'd take a little while because we're getting it for free.

**Comment by pazos** [comment]
Yeah, the format is supported. It is called IOS strings (I assumed it was xliff but weblate docs say that xliff is just xml, and that's not the case here).

>  I think it'd need to be a different component. Which we probably can get but it'd take a little while because we're getting it for free.

It is a PITA just to translate a few strings (15 or so). Even more, probably these strings will never change. And even worst, apple won't support part of the languages already supported by KOReader.

**Comment by Frenzie** [comment]
I suppose we can just leave it GH-only for the moment.

**Comment by pazos** [comment]
> I suppose we can just leave it GH-only for the moment.

And submit new languages to this repo?. Sounds good to me.

**Comment by Frenzie** [comment]
@pazos That Mac thing still good? I didn't realize this PR wasn't merged yet, cf. https://github.com/koreader/koreader/pull/6870#discussion_r522185920

**Review by Frenzie — APPROVED** [review]
So please merge if it's good to go. ^_^

**Pull request merged**
