### PR TITLE
Update en_GB

### PR DESCRIPTION
**Pull request by cheywood**
Actually, while I'm here, a question: is there a way to get notified when strings are frozen before each KOReader release?

This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-translations/170)

### CODE REVIEW

**Comment by Frenzie** [comment]
We don't work that formally. There is a period you might call a freeze but it simply consists of trying not to add any new strings (or big changes in general) for about a week, which in combination with Weblate notifications about new strings means the actively translated languages will normally be fully translated. We haven't needed more than that.

**Comment by cheywood** [comment]
> We don't work that formally.

And there's nothing wrong with that :+1: :smile:

> There is a period you might call a freeze 

Is there a way to know roughly when that is / when a release is about to happen? I'm not generally a translator, providing an update for each release would be easier than every time a string changes.

If not, that's fine too :)

**Comment by Frenzie** [comment]
I could try to remember to ping you but other than that probably not. In principle if it's been more than three weeks I try to move towards a release but right now I'm not entirely convinced it's quite ready yet. But I think we should be close.

**Comment by Frenzie** [comment]
But the Weblate notifications can be set up. I think I only receive a weekly digest for changed strings and an immediate notification for comments. I may have tweaked some of that slightly but I think it should be fairly close to the default.

**Comment by cheywood** [comment]
> I could try to remember to ping you

Nah I think it would be pretty hard to justify that effort for an English to English translation :laughing: 

All good, thanks for thinking through it. I understand my workflow's a corner case compared to proper translators :pray:

**Pull request merged**
