### PR TITLE
Translated using PoEdit (Italian)

### PR DESCRIPTION
**Pull request by M0Rf30**
Currently translated at 100% (2742 of 2742 strings)

---
This change is [Reviewable](https://reviewable.io/reviews/koreader/koreader-translations/137)

### CODE REVIEW

**Comment by Frenzie** [comment]
Thanks!

**Comment by M0Rf30** [comment]
Thanks to you for this amazing project. Hope that you can unlock the weblate repo counterpart

**Comment by Frenzie** [comment]
I'm not quite sure what you mean?

**Comment by Frenzie** [comment]
Oh, merging this caused a conflict? :-/

I won't have time to look at that until the weekend. Perhaps @NiLuJe will have time earlier.

**Comment by M0Rf30** [comment]
> I'm not quite sure what you mean?

Have a look here https://hosted.weblate.org/projects/koreader/koreader/#alerts to understand. Its quite common on Weblate Continuous Localization flow. Now KOReader project on Weblate is simply locked and nobody can translate until you unlock it

**Comment by Frenzie** [comment]
It's never happened here before but perhaps we just got lucky. I think it should be mostly avoidable by telling Weblate to commit everything first and only then to merge a PR but I didn't realize I needed to do that.

**Comment by Frenzie** [comment]
@M0Rf30 I resolved the conflict. If I made the wrong choice for this one, could you please update it?

```diff
#: frontend/apps/reader/modules/readerfooter.lua:1438
msgid "Hide battery status if level higher than: %1%"
-msgstr "Nascondi stato della batteria ad un livello superiore di: %1%"
+msgstr "Nascondi lo stato della batteria se il livello è superiore a: %1%"
```

**Comment by M0Rf30** [comment]
Thank you so much for your efforts. I will continue the refinement work from weblate interface in order to minimize this kind of troubles. Regards

**Comment by Frenzie** [comment]
Please feel free to use POEdit if you prefer. I know now. ^_^

That being said, I should maybe try to make it a little more foolproof, in case I forget in a few months or just for someone else.

**Pull request merged**
